name: Kiwi Browser Automated Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday 00:00 UTC

env:
  BUILD_DIR: out/Release
  APK_PREFIX: KiwiBrowser
  ANDROID_TARGETS: "arm64 x64"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      # ============== SPARSE CHECKOUT ==============
      - name: Configure sparse checkout
        run: |
          git config --global core.sparseCheckout true
          git config --global core.sparseCheckoutCone false
          mkdir -p .git/info
          echo "/*" > .git/info/sparse-checkout
          echo "!third_party/*" >> .git/info/sparse-checkout
          echo "!tools/*" >> .git/info/sparse-checkout
          echo "!docs/*" >> .git/info/sparse-checkout

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: OutlinedArc217/kiwi-broken
          token: ${{ secrets.GH_TOKEN }}
          path: src
          fetch-depth: 1
          sparse-checkout: |
            /*
            !third_party/*
            !tools/*
            !docs/*

      # ============== ENVIRONMENT SETUP ==============
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 python3-pip ninja-build \
            libncurses5 libglib2.0-0 libnss3 \
            openjdk-11-jdk-headless
          sudo update-java-alternatives --set java-1.11.0-openjdk-amd64

          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH

      # ============== CODE MERGING ==============
      - name: Merge Chromium updates
        working-directory: ./src
        run: |
          git config user.name "Kiwi AutoMerger"
          git config user.email "automerger@kiwibrowser.com"
          
          if ! git remote | grep -q chromium; then
            git remote add chromium https://chromium.googlesource.com/chromium/src
          fi

          git fetch chromium --tags --depth=1
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          
          git merge $LATEST_TAG -X ours --no-commit || true
          git commit -m "Merge Chromium $LATEST_TAG" || echo "No changes to commit"

      # ============== BUILD CONFIGURATION ==============
      - name: Generate build configs
        working-directory: ./src
        run: |
          for arch in $ANDROID_TARGETS; do
            mkdir -p out/$arch
            cat << EOF > out/$arch/args.gn
            target_os = "android"
            target_cpu = "$arch"
            is_debug = false
            is_official_build = true
            symbol_level = 1
            android_default_version_code = "$(date +%Y%m%d)"
            android_keystore_name = "release"
            android_keystore_password = "${{ secrets.KEY_STORE_PASSWORD }}"
            android_keystore_path = "../../../keystore.jks"
            EOF
          done

      # ============== PARALLEL BUILD ==============
      strategy:
        matrix:
          arch: [arm64, x64]
        fail-fast: false

      - name: Build APK (${{ matrix.arch }})
        working-directory: ./src
        run: |
          gn gen out/${{ matrix.arch }} --args="$(cat out/${{ matrix.arch }}/args.gn)"
          autoninja -C out/${{ matrix.arch }} chrome_public_apk -j $(nproc)

      # ============== ARTIFACT PROCESSING ==============
      - name: Sign APKs
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: src/out
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          apkSigningScheme: v2
          apkPaths: |
            **/ChromePublic.apk

      - name: Package artifacts
        run: |
          find src/out -name "ChromePublic.apk" -exec sh -c '
            dir=$(dirname {})
            arch=$(basename $dir)
            mv {} src/out/${{ env.APK_PREFIX }}_${arch}_$(date +%Y%m%d).apk
          ' \;

      # ============== RELEASE PUBLISHING ==============
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src/out/*.apk
          tag_name: kiwi-${{ github.run_id }}
          name: "Kiwi Build $(date +%F)"
          body: |
            **Build Details**
            - Chromium Version: $(grep '^LASTCHANGE=' src/build/util/LASTCHANGE | cut -d'=' -f2)
            - Build Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
            - Target Architectures: ${{ env.ANDROID_TARGETS }}
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
