name: Kiwi Browser Auto Build

on:
  workflow_dispatch:
    inputs:
      prepareRelease:
        description: 'Publish to Google Play Store'
        required: true
        default: 'no'
  schedule:
    - cron: '0 0 * * 1'  # 每周一 UTC 0 点自动触发
  push:
    branches: [main]

jobs:
  sync_chromium:
    name: Sync Chromium Code
    runs-on: ubuntu-20.04
    steps:
      # ------------------------- 拉取 Kiwi 代码 -------------------------
      - name: Checkout Kiwi
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 需要完整提交历史

      # ------------------------- 配置 Chromium 远程仓库 -------------------------
      - name: Add Chromium Remote
        run: |
          git remote add chromium https://chromium.googlesource.com/chromium/src
          git fetch chromium --tags --force

      # ------------------------- 自动合并代码 -------------------------
      - name: Merge Chromium Updates
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 获取最新 Chromium 稳定版标签
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          
          # 尝试自动合并（优先保留 Kiwi 修改）
          git merge $LATEST_TAG -X theirs --no-commit || true
          
          # 提交合并结果
          git commit -m "Merge Chromium $LATEST_TAG" --allow-empty
          git push origin HEAD:auto-merge

  build:
    name: Build APKs
    needs: sync_chromium
    runs-on: ubuntu-20.04
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        platform: [arm, arm64, x86, x64]

    steps:
      # ------------------------- 获取合并后的代码 -------------------------
      - name: Checkout Merged Code
        uses: actions/checkout@v2
        with:
          ref: auto-merge  # 使用自动合并分支

      # ------------------------- 签名配置 -------------------------
      - name: Setup Signing Key
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          echo "$SIGNING_KEY" | base64 -d > keystore.jks
          ls -la keystore.jks

      # ------------------------- 构建环境 -------------------------
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python openjdk-8-jdk-headless libncurses5 ccache ninja-build

      # ------------------------- 构建参数 -------------------------
      - name: Configure GN Args
        run: |
          mkdir -p out/android_${{ matrix.platform }}
          cat <<EOF > out/android_${{ matrix.platform }}/args.gn
          target_os = "android"
          target_cpu = "${{ matrix.platform }}"
          is_debug = false
          is_official_build = true
          android_keystore_name = "${{ secrets.ALIAS }}"
          android_keystore_password = "${{ secrets.KEY_STORE_PASSWORD }}"
          android_keystore_path = "../../../keystore.jks"
          EOF

      # ------------------------- 编译APK -------------------------
      - name: Build APK
        run: |
          gn gen out/android_${{ matrix.platform }}
          autoninja -C out/android_${{ matrix.platform }} chrome_public_apk

      # ------------------------- 签名APK -------------------------
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: out/android_${{ matrix.platform }}/apks
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # ------------------------- 发布产物 -------------------------
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: kiwi-${{ matrix.platform }}-${{ github.run_id }}
          path: out/android_${{ matrix.platform }}/apks/ChromePublic.apk

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*.apk
          tag_name: v${{ github.run_id }}
          name: "Kiwi Build ${{ github.run_id }} (Chromium $(grep '^LASTCHANGE=' build/util/LASTCHANGE | cut -d'=' -f2))"
          body: |
            ### Auto-merged Chromium Version
            - Merged Chromium Tag: $(git describe --tags $(git rev-list --tags --max-count=1))
            - Build Timestamp: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
